#include "stdafx.h"
#include "gameobject_type.h"
#include "../../Expansion/log.h"

int GetGameobjectTypeById(GameobjectId gameobjectId) {
	switch (gameobjectId) {
	case GAMEOBJECT_BABA:
	case GAMEOBJECT_KEKE:
		return OBJECT_TYPE_CHARACTER;

	case GAMEOBJECT_SKULL:
	case GAMEOBJECT_CRAB:
		return OBJECT_TYPE_DIRECTIONAL;

	case GAMEOBJECT_WALL:
	case GAMEOBJECT_WATER:
	case GAMEOBJECT_LAVA:
	case GAMEOBJECT_GRASS:
	case GAMEOBJECT_BRICK:
	case GAMEOBJECT_ICE:
	case GAMEOBJECT_HEDGE:
		return OBJECT_TYPE_TILED;

	case GAMEOBJECT_ROCK:
	case GAMEOBJECT_FLAG:
	case GAMEOBJECT_TILE:
	case GAMEOBJECT_FLOWER:
	case GAMEOBJECT_JELLY:
	case GAMEOBJECT_ALGAE:
	case GAMEOBJECT_STAR:
	case GAMEOBJECT_LOVE:
	case GAMEOBJECT_PILLAR:
	case GAMEOBJECT_KEY:
	case GAMEOBJECT_DOOR:
	case GAMEOBJECT_BUBBLE:
		return OBJECT_TYPE_STATIC;

	case GAMEOBJECT_TEXT_IS:
	case GAMEOBJECT_TEXT_AND:

	case GAMEOBJECT_TEXT_BABA:
	case GAMEOBJECT_TEXT_WALL:
	case GAMEOBJECT_TEXT_FLAG:
	case GAMEOBJECT_TEXT_ROCK:
	case GAMEOBJECT_TEXT_WATER:
	case GAMEOBJECT_TEXT_SKULL:
	case GAMEOBJECT_TEXT_LAVA:
	case GAMEOBJECT_TEXT_GRASS:
	case GAMEOBJECT_TEXT_JELLY:
	case GAMEOBJECT_TEXT_ALGAE:
	case GAMEOBJECT_TEXT_CRAB:
	case GAMEOBJECT_TEXT_STAR:
	case GAMEOBJECT_TEXT_KEKE:
	case GAMEOBJECT_TEXT_LOVE:
	case GAMEOBJECT_TEXT_PILLAR:
	case GAMEOBJECT_TEXT_KEY:
	case GAMEOBJECT_TEXT_DOOR:
	case GAMEOBJECT_TEXT_HEDGE:

	case GAMEOBJECT_TEXT_YOU:
	case GAMEOBJECT_TEXT_PUSH:
	case GAMEOBJECT_TEXT_STOP:
	case GAMEOBJECT_TEXT_WIN:
	case GAMEOBJECT_TEXT_SINK:
	case GAMEOBJECT_TEXT_DEFEAT:
	case GAMEOBJECT_TEXT_HOT:
	case GAMEOBJECT_TEXT_MELT:
	case GAMEOBJECT_TEXT_SHUT:
	case GAMEOBJECT_TEXT_OPEN:
	case GAMEOBJECT_TEXT_MOVE:
		return OBJECT_TYPE_TEXT;

	default:
		Log::LogError("%s didn't has gameobject type", GetGameobjectNameById(gameobjectId).c_str());
		return -1;
	}
}