#pragma once

#include <unordered_map>
#include "game_level_config.h"

#define OPERATOR_TEXTOBJECT_BEGIN		TEXTOBJECT_ID_BEGIN
#define GAMEOBJECT_TEXTOBJECT_BEGIN		TEXTOBJECT_ID_BEGIN + 100
#define PROPERTY_TEXTOBJECT_BEGIN		TEXTOBJECT_ID_BEGIN + 600

enum ObjectId {
	OBJECT_NONE = GAMEOBJECT_ID_BEGIN,
	OBJECT_CROSSED,
	GAMEOBJECT_TEXTS,
	GAMEOBJECT_BABA,
	GAMEOBJECT_FLAG,
	GAMEOBJECT_WALL,
	GAMEOBJECT_ROCK,
	GAMEOBJECT_TILE,
	GAMEOBJECT_GRASS,
	GAMEOBJECT_WATER,
	GAMEOBJECT_SKULL,
	GAMEOBJECT_LAVA,
	GAMEOBJECT_FLOWER,
	GAMEOBJECT_BRICK,
	GAMEOBJECT_ICE,
	GAMEOBJECT_JELLY,
	GAMEOBJECT_ALGAE,
	GAMEOBJECT_CRAB,
	GAMEOBJECT_SATR,
	GAMEOBJECT_KEKE,
	GAMEOBJECT_LOVE,
	GAMEOBJECT_PILLAR,
	GAMEOBJECT_BUBBLE,
	GAMEOBJECT_KEY,
	GAMEOBJECT_DOOR,
	GAMEOBJECT_HEDGE,
	GAMEOBJECT_ROSE,
	GAMEOBJECT_VIOLET,
	GAMEOBJECT_COG,
	GAMEOBJECT_PIPE,
	GAMEOBJECT_ROBOT,
	GAMEOBJECT_BOLT,
	GAMEOBJECT_REED,
	GAMEOBJECT_BOG,
	GAMEOBJECT_BOX,
	GAMEOBJECT_HUSK,
	GAMEOBJECT_STUMP,
	GAMEOBJECT_TREE,
	GAMEOBJECT_GHOST,
	GAMEOBJECT_STATUE,
	
	TEXTOBJECT_IS = OPERATOR_TEXTOBJECT_BEGIN,
	TEXTOBJECT_AND,
	TEXTOBJECT_HAS,

	TEXTOBJECT_TEXT = GAMEOBJECT_TEXTOBJECT_BEGIN,
	TEXTOBJECT_BABA,
	TEXTOBJECT_FLAG,
	TEXTOBJECT_WALL,
	TEXTOBJECT_ROCK,
	TEXTOBJECT_TILE,
	TEXTOBJECT_GRASS,
	TEXTOBJECT_WATER,
	TEXTOBJECT_SKULL,
	TEXTOBJECT_LAVA,
	TEXTOBJECT_FLOWER,
	TEXTOBJECT_BRICK,
	TEXTOBJECT_ICE,
	TEXTOBJECT_JELLY,
	TEXTOBJECT_ALGAE,
	TEXTOBJECT_CRAB,
	TEXTOBJECT_STAR,
	TEXTOBJECT_KEKE,
	TEXTOBJECT_LOVE,
	TEXTOBJECT_PILLAR,
	TEXTOBJECT_BUBBLE,
	TEXTOBJECT_KEY,
	TEXTOBJECT_DOOR,
	TEXTOBJECT_HEDGE,
	TEXTOBJECT_ROSE,
	TEXTOBJECT_VIOLET,
	TEXTOBJECT_COG,
	TEXTOBJECT_PIPE,
	TEXTOBJECT_ROBOT,
	TEXTOBJECT_BOLT,
	TEXTOBJECT_REED,
	TEXTOBJECT_BOG,
	TEXTOBJECT_BOX,
	TEXTOBJECT_HUSK,
	TEXTOBJECT_STUMP,
	TEXTOBJECT_TREE,
	TEXTOBJECT_GHOST,
	TEXTOBJECT_STATUE,

	TEXTOBJECT_YOU = PROPERTY_TEXTOBJECT_BEGIN,
	TEXTOBJECT_WIN,
	TEXTOBJECT_STOP,
	TEXTOBJECT_PUSH,
	TEXTOBJECT_SINK,
	TEXTOBJECT_DEFEAT,
	TEXTOBJECT_MELT,
	TEXTOBJECT_HOT,
	TEXTOBJECT_MOVE,
	TEXTOBJECT_SHUT,
	TEXTOBJECT_OPEN,
	TEXTOBJECT_RED,
	TEXTOBJECT_BLUE,
	TEXTOBJECT_FLOAT,
	TEXTOBJECT_WEAK,
};

class ObjectIdProc {
private:
	static std::unordered_map<std::string, ObjectId> objectNameAndId;

public:
	static bool IsGameobjectId(int id);
	static bool IsGameobjectId(std::string name);
	static bool IsTextobjectId(int id);
	static bool IsTextobjectId(std::string name);

	static ObjectId GetIdByName(std::string gameobjectName);
	static std::string GetNameById(ObjectId gameobjectId);
};